# Generated by Django 4.2.1 on 2023-05-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='category_name')),
                ('category_description', models.TextField(verbose_name='category_description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='product_name')),
                ('description', models.TextField(verbose_name='product_description')),
                ('img', models.ImageField(upload_to='media/', verbose_name='product_img')),
                ('category', models.CharField(max_length=50, verbose_name='product_category')),
                ('price', models.IntegerField(verbose_name='product_price')),
                ('creation_date', models.DateTimeField(verbose_name='product_creation_date')),
                ('last_change_date', models.DateTimeField(verbose_name='product_clast_change_date')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('name',),
            },
        ),
    ]
