# Generated by Django 4.2.1 on 2023-05-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='company_name')),
                ('address', models.TextField(verbose_name='company_address')),
                ('phone', models.CharField(max_length=50, verbose_name='company_phone')),
                ('email', models.CharField(max_length=50, verbose_name='company_email')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
            },
        ),
    ]
